version: '3.1'
services: 
  
  db:
    image: postgres:11.3
    container_name: cms_db
    restart: always
    volumes:
      - cms_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: 'root'
    
  backend:
    image: sbesh91/rust-cms:latest
    container_name: cms_backend
    restart: always
    volumes:
      - ./.env:/usr/src/rust-cms/.env
  
  frontend:
    image: sbesh91/rust-cms-frontend:latest
    container_name: cms_frontend
    restart: always

  nginx:
    image: nginx:1.15.8
    container_name: nginx
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports: 
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443

  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes:
  cms_db_data:
  cms_cache_data: